# site_name: FastGQL
# theme:
  # name: material

# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: FastGQL
site_url: https://jerber.github.io/fastgql/
site_description: FastGQL is a python GraphQL framework that is high performance, easy to learn and ready for production.
theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    # FROM FASTAPI
    - search.suggest
    - search.highlight
    - navigation.instant
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    # - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select


    # FROM TUTORIAL
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    # - content.code.annotation
    # - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  logo: 'img/emoji_logo.svg'
  favicon: 'img/emoji_logo.svg'
  language: en
repo_name: 'jerber/fastgql'
repo_url: 'https://github.com/jerber/fastgql'
edit_uri: ''
nav:
  - FastGQL: index.md
  - Tutorial - User Guide:
    - tutorial/index.md
    - tutorial/more_advanced.md

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jerber
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jerber888
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jeremyberman1/

# markdown_extensions:
# - toc:
#     permalink: true
# - pymdownx.superfences:
#     custom_fences:
#     - name: mermaid
#       class: mermaid
#       format: !!python/name:pymdownx.superfences.fence_code_format ''
# - pymdownx.tabbed:
#     alternate_style: true

# markdown_extensions:
# - pymdownx.snippets:
#       base_path: ['docs']
#       check_paths: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_include

# this is SQLMODEL
# markdown_extensions:
# - toc:
#     permalink: true
# - markdown.extensions.codehilite:
#     guess_lang: false
# - admonition
# - codehilite
# - extra
# - pymdownx.superfences:
#     custom_fences:
#     - name: mermaid
#       class: mermaid
#       format: !!python/name:pymdownx.superfences.fence_code_format ''
# - pymdownx.tabbed:
#     alternate_style: true
# - mdx_include

extra_css:
  - stylesheets/extra.css
