name: Build and Release

on:
  push:
    branches:
      - main  # Run workflow on pushes to main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      # Disable actions/cache usage
      ACTIONS_SETUP_PYTHON_DISABLE_CACHE: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine
          pip install -e .
          
      - name: Build package
        run: |
          python -m build
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true