name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v4
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine
          pip install -e .
          
      - name: Build package
        run: |
          python -m build
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*